package com.paylite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgentCardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentCardAllPropertiesEquals(AgentCard expected, AgentCard actual) {
        assertAgentCardAutoGeneratedPropertiesEquals(expected, actual);
        assertAgentCardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentCardAllUpdatablePropertiesEquals(AgentCard expected, AgentCard actual) {
        assertAgentCardUpdatableFieldsEquals(expected, actual);
        assertAgentCardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentCardAutoGeneratedPropertiesEquals(AgentCard expected, AgentCard actual) {
        assertThat(actual)
            .as("Verify AgentCard auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentCardUpdatableFieldsEquals(AgentCard expected, AgentCard actual) {
        assertThat(actual)
            .as("Verify AgentCard relevant properties")
            .satisfies(a -> assertThat(a.getPan()).as("check pan").isEqualTo(expected.getPan()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getExpireDate()).as("check expireDate").isEqualTo(expected.getExpireDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentCardUpdatableRelationshipsEquals(AgentCard expected, AgentCard actual) {
        assertThat(actual)
            .as("Verify AgentCard relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()));
    }
}
