package com.paylite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class P2POperationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertP2POperationAllPropertiesEquals(P2POperation expected, P2POperation actual) {
        assertP2POperationAutoGeneratedPropertiesEquals(expected, actual);
        assertP2POperationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertP2POperationAllUpdatablePropertiesEquals(P2POperation expected, P2POperation actual) {
        assertP2POperationUpdatableFieldsEquals(expected, actual);
        assertP2POperationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertP2POperationAutoGeneratedPropertiesEquals(P2POperation expected, P2POperation actual) {
        assertThat(actual)
            .as("Verify P2POperation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertP2POperationUpdatableFieldsEquals(P2POperation expected, P2POperation actual) {
        assertThat(actual)
            .as("Verify P2POperation relevant properties")
            .satisfies(a -> assertThat(a.getRequestId()).as("check requestId").isEqualTo(expected.getRequestId()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getCommissionAmount()).as("check commissionAmount").isEqualTo(expected.getCommissionAmount()))
            .satisfies(a -> assertThat(a.getTotalAmount()).as("check totalAmount").isEqualTo(expected.getTotalAmount()))
            .satisfies(a -> assertThat(a.getFromPan()).as("check fromPan").isEqualTo(expected.getFromPan()))
            .satisfies(a -> assertThat(a.getFromType()).as("check fromType").isEqualTo(expected.getFromType()))
            .satisfies(a -> assertThat(a.getFromExpireDate()).as("check fromExpireDate").isEqualTo(expected.getFromExpireDate()))
            .satisfies(a -> assertThat(a.getToPan()).as("check toPan").isEqualTo(expected.getToPan()))
            .satisfies(a -> assertThat(a.getToType()).as("check toType").isEqualTo(expected.getToType()))
            .satisfies(a -> assertThat(a.getToExpireDate()).as("check toExpireDate").isEqualTo(expected.getToExpireDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFailureReason()).as("check failureReason").isEqualTo(expected.getFailureReason()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertP2POperationUpdatableRelationshipsEquals(P2POperation expected, P2POperation actual) {
        // empty method
    }
}
